exclude = [ 
    "OLD",
    "OTHER",
    ".git",
    ".idea",
    ".mypy_cache",
    ".tox",
    ".venv"
]
target-version = "py310"

line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[lint.isort]
split-on-trailing-comma = false

[lint.pylint]
max-args = 10  # or any other number greater than 9

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"test_*" = ["S101", "D101", "D102", "D103", "F811", "PT006", "PT011"]
"tests/*" = ["S101", "D101", "D102", "D103", "F811", "PT006", "PT011"]

[lint.mccabe]
# Flake8 is 15 - which I feel is too high
max-complexity = 10

[lint]
exclude = ["docs/source/conf.py","*.pyi"]

dummy-variable-rgx = "^(dummy_.*|unused_.*|_)$"

select = ["ALL"]

fixable = ["ALL"]
unfixable = []

# Ignore these when needed
# "A001"      # builtin-variable-shadowing
# "ERA001",   # commented-out-code
# "E501",     # line-too-long
# "PLR2004"   # magic-value-comparison
# "SLF001",   # private-member-access
# "SLOT000"   # no-slots-in-str-subclass
# "TCH001",   # typing-only-first-party-import
# "TCH002"    # typing-only-third-party-import

ignore = [
    "ISC001", # implicit-str-concat
    "COM812", # missing-trailing-comma

    # ALLOW PICKLE USE
    "S301",  # `pickle` and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue

    # IGNORE TODO
    "TD002",  # Missing author in TODO; try: `# TODO(<author_name>): ...` or `# TODO @<author_name>: ...`
    "TD003",  # Missing issue link on the line following this TODO
    "FIX002",  # Line contains TODO, consider resolving the issue

    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument
    "FBT003",  # Boolean positional value in function call
    
    # "T201",  # `print` found
    
    "NPY002",  # Replace legacy `np.random.permutation` call with `np.random.Generator.permutation`
    
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`

    ## WE NEED TO REMOVE THESE LATER

    # EXCEPTIONS
    "EM101",  # Exception must not use a string literal, assign to variable first
    "EM102",  # Exception must not use an f-string literal, assign to variable first
    "TRY003",  # Avoid specifying long messages outside the exception class
    "TRY300", # Use of else blocks in try/except

    # DOCSTRINGS
    #"D102",  # Missing docstring in public method
    #"D103",  # Missing docstring in public function
    "D105",  # Missing docstring in magic method
    # "D107",  # Missing docstring in `__init__`
    #"D415",  # First line should end with a period, question mark, or exclamation point
]

